<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_全選</name>
   <tag></tag>
   <elementGuidId>2a6a46c5-1ab6-49d5-b595-4e31ac14b48f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='處理中'])[1]/preceding::span[6]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '全選' or . = '全選')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.ant-checkbox-wrapper.ant-checkbox-wrapper-checked > span:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ded8e91e-983b-4376-98f6-96a3fee4ac4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>全選</value>
      <webElementGuid>ddd3529a-28ed-4c18-9c7c-177d6450add4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;search-container&quot;]/div[@class=&quot;search-option-block&quot;]/div[@class=&quot;option-container application-container&quot;]/label[@class=&quot;ant-checkbox-wrapper ant-checkbox-wrapper-checked&quot;]/span[2]</value>
      <webElementGuid>5ac24619-8502-42fa-a7b2-8b5789316831</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/main/div[2]/div/div[4]/div/label/span[2]</value>
      <webElementGuid>fa99247c-76d1-44c0-b963-549faf2ec357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='申請狀態'])[1]/following::span[3]</value>
      <webElementGuid>3e30b267-3f1e-425c-964f-8f42a67e9b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='申請類型'])[2]/following::span[3]</value>
      <webElementGuid>c832d8a3-98f7-4541-97a4-994aa35710e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='待處理'])[1]/preceding::span[3]</value>
      <webElementGuid>5352652a-381c-421f-9e46-8bc213c61c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='處理中'])[1]/preceding::span[6]</value>
      <webElementGuid>e5c8c3f8-7852-4dd0-a371-94de72774175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='全選']/parent::*</value>
      <webElementGuid>613ed623-6fe6-43cf-b940-8243e6a03b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span[2]</value>
      <webElementGuid>1281d07e-1301-4b05-9962-5f3db3214e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '全選' or . = '全選')]</value>
      <webElementGuid>ab6cd653-99bd-41f8-a27a-0915220739ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
