<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>申請購買與部署憑證 - Happy Path</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7620624c-9735-493a-8295-0e78d7a80386</testSuiteGuid>
   <testCaseLink>
      <guid>930b7327-fde2-40cd-aeb6-4088f493b910</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Case/建站管理系統登入</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4d89d69-6e64-4717-9608-e9255089b9d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91755d3c-b49b-4ab0-b91b-a59d73f88d64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66ee1bb6-2102-4f17-844f-49e500220bfd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9ac216e-57fb-497f-b723-6e6d5c220f30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01. 申請廳主買域名/申請廳主買域名</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>68115da3-5665-4acd-bce1-76b92c142e7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/03. 申請購買與部署憑證/申請購買憑證</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>177c2aaa-5905-477b-914c-29ee98e3d0fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0cac65e-37cb-4c0b-b260-e55feba6fb74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Case/workflow 頁檢查申請資訊</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b3b30cd-a55f-4e20-844e-6a47d3f04d0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a6d7e8a-c568-4f28-9bb7-f1453cc7d7d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ed55ef9-778f-42aa-9132-a61585f56bcd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4eaeeb25-70a5-4d47-aad6-3ef41d0ec033</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Case/測試後刪除域名</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6d41e91-293f-4bca-adff-555d22d0f623</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70b82426-11b0-45a8-985a-8b34633bddad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02140afe-4796-4013-9e7e-cddb500acf1f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
