<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_user</name>
   <tag></tag>
   <elementGuidId>e7962b0e-efae-4241-95a7-cef9cbf321f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_user</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
