<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_record</name>
   <tag></tag>
   <elementGuidId>2acd8479-e22e-4d4a-821f-3b0d4e9d9567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rc-tabs-0-tab-2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
