<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>02.申請購買憑證</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d29d29bc-877b-4500-b6bd-631d9597c17c</testSuiteGuid>
   <testCaseLink>
      <guid>a81fffe7-dbb3-4657-84d1-748fcc69baab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CommonTest/建站管理系統登入</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4d89d69-6e64-4717-9608-e9255089b9d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91755d3c-b49b-4ab0-b91b-a59d73f88d64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66ee1bb6-2102-4f17-844f-49e500220bfd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87921a3e-dd42-453b-8027-7c322cbfc374</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/搜索類型-申請類型/02.申請購買憑證</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>177c2aaa-5905-477b-914c-29ee98e3d0fb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
