<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_google</name>
   <tag></tag>
   <elementGuidId>c1a84a7d-d6e7-4f6d-b741-5ed6feb1c085</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.abcRioButtonContentWrapper</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
