<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>搜尋類型-域名</description>
   <name>div_域名</name>
   <tag></tag>
   <elementGuidId>9623428c-9baa-401a-a22e-631b6a18e72c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[title='域名'] div[class='ant-select-item-option-content']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '域名' or . = '域名')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c4ebf6b5-491f-4442-8fba-dee6958c05d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>828ede6b-c8c1-48aa-9ab6-b9697dee849c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>域名</value>
      <webElementGuid>fd9092fd-a3e6-438b-a2ed-cd646fc423dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[1]/div[@class=&quot;ant-select-dropdown ant-select-dropdown-placement-bottomLeft&quot;]/div[1]/div[@class=&quot;rc-virtual-list&quot;]/div[@class=&quot;rc-virtual-list-holder&quot;]/div[1]/div[@class=&quot;rc-virtual-list-holder-inner&quot;]/div[@class=&quot;ant-select-item ant-select-item-option ant-select-item-option-active ant-select-item-option-selected&quot;]/div[@class=&quot;ant-select-item-option-content&quot;]</value>
      <webElementGuid>6dd4a650-d2a6-4879-9c03-792ffbf2cb3b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
